server:
    tomcat:
        threads:
            max: 200 # Maximum amount of worker threads.
        max-connections: 8192 # default size is 8192

spring:
    application:
        name: spring-load-generator
    datasource:
        url: jdbc:postgresql://localhost:5432/
        username: postgres
        password: postgres
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher # required for the Swagger UI to work

logging:
    config: classpath:logback-spring.xml

management:
    endpoints:
        web:
            exposure:
                include: "*"

issuer-verifier:
    acapy:
        api-key:
        url: 'http://localhost:10000'
        http-timeout-in-seconds: 60
    multitenancy:
        enabled: false
        wallet-type: askar
        register-did-endpoint: http://localhost:9000/register
        webhook-endpoint-url: http://host.docker.internal:8080/acapy-webhook
        sub-wallet-name: host.docker.internal
    wallet-db-name: wallet_db

holder:
    acapy:
        api-key:
        urls: 'http://localhost:10010'
        http-timeout-in-seconds: 60

test-runners:
    max-parallel-iterations-runner:
        active: false
        number-of-total-iterations: 100
        number-of-parallel-iterations: 5
    constant-load-runner:
        active: true
        number-of-total-iterations: 100
        number-of-iterations-per-minute: 30
        thread-pool-size: 4
    increasing-load-runner:
        active: false
        peak-duration-in-minutes: 2
        sleep-between-peaks-in-minutes: 1
        initial-number-of-iterations-per-minute: 150
        final-number-of-iterations-per-minute: 500
        step-size-of-iterations-per-minute: 25
        thread-pool-size: 4

test-flows:
    empty-flow:
        active: false
    full-flow:
        active: true
        use-revocable-credentials: true
        revocation-registry-size: 500
        check-non-revoked: true
        revoke-credentials: true
        credential-revocation-batch-size: 5
        use-oob-instead-of-connection: false
    issuer-flow:
        active: false
        use-revocable-credentials: true
        revocation-registry-size: 500
        use-oob-credential-issuance: false
    connection-flow:
        active: false
    credential-issuance-flow:
        active: false
        use-revocable-credentials: true
        revocation-registry-size: 500
        use-oob-credential-issuance: false
    proof-request-flow:
        active: false
        check-non-revoked: true
        revocation-registry-size: 500
        use-oob-proof-requests: false
