spring:
    datasource:
        url: jdbc:postgresql://issuer-verifier-wallet-db:5000/

logging:
    config: classpath:logback-spring-docker.xml

issuer-verifier:
    acapy:
        url: 'http://issuer-verifier-acapy:10000'
    multitenancy:
        register-did-endpoint: http://von_webserver_1:9000/register
        webhook-endpoint-url: http://load-generator-1:8080/acapy-webhook

holder:
    acapy:
        urls: 'http://holder-acapy:10010'
